### ISSUE TITLE
v1.3.1 64-sample-long chains won't export

### ISSUE THREAD

**Issue by spreadpando** [KaiDrange/OctaChainer#13]
Platform: windows 10
Version: 1.3.1
Sample Chains of length 64 alert "Warning: more than 64 chains" and "This will create multiple wav files. Continue?"
I believe there is a bug where this alert fires too soon, when the chain is exactly 64 slices long, instead of _over_ 64 slices in length.

The program fails to produce a second wav file or a single .ot file.
 I've also experienced missing .ot files unplayable wavs when exporting 64-slice-long chains from version 1.3.0.
 
Finally the alert would make more sense were it to say "Warning: more than 64 _slices_" (instead of chains).

**Comment by KaiDrange** [comment]
Thank you for letting me know. Fixed. I should probably create a new release before too long, as this issue sounds annoying.

**Comment by spreadpando** [comment]
Nice! I'd personally love a new release. Havnen't dabbled with QT or really much C++ for that matter, I didn't get far past downloading QT before I bailed back to ableton. I've literally just started making 63 slice long samples with it instead but I like to use all 64 so I can make full use of the LFOs on the Start param:) The features here save me hours.
